/**
 * Semantic parts <-> model nodes.
 *
 * The app talks about a `rearTrunk`; the asset contains a node called
 * `hinge_liftgate`. This file is the only place those two vocabularies meet, so
 * swapping in a different vehicle asset means editing this table and nothing
 * else. The values are generated by tools/build_vehicle_model.py and mirrored
 * into assets/vehicle/vehicle.articulation.json — see docs/ASSETS.md.
 */

import type { DoorId, VehicleState } from '@/domain/entities';

/** Every part of the vehicle the app can address. */
export type VehiclePart =
  | 'driverDoor'
  | 'passengerDoor'
  | 'rearLeftDoor'
  | 'rearRightDoor'
  | 'rearTrunk'
  | 'frontTrunk'
  | 'chargePort';

export type HingeAxis = 'x' | 'y' | 'z';

export type HingeSpec = {
  /** Node name in the glTF scene graph. */
  node: string;
  axis: HingeAxis;
  /** Rotation in degrees that corresponds to fully open. Sign matters. */
  openDegrees: number;
  /** Where the hinge sits, in normalised model space. Also places hotspots. */
  pivot: readonly [number, number, number];
  /**
   * How the hinge is realised.
   *
   * 'node'  the node's own origin IS the hinge, so rotating it is correct.
   *         True for the bundled model and for any properly rigged asset.
   * 'wrap'  the node's origin is somewhere else (commonly the model origin),
   *         so rotating it would swing the door around the middle of the car.
   *         The loader then re-parents it under a group placed at `pivot`.
   *
   * Most commercial assets need 'wrap'. Check with tools/inspect_model.py: if a
   * door's node sits at (0, 0, 0) rather than out at the A-pillar, use 'wrap'.
   */
  pivotMode?: 'node' | 'wrap';
  /** Human label. "Rear trunk", not "liftgate". */
  label: string;
};

export const HINGES: Record<VehiclePart, HingeSpec> = {
  driverDoor: {
    node: 'hinge_doorFrontLeft',
    axis: 'y',
    openDegrees: 64,
    pivot: [-0.905, 0.76, 0.955],
    label: 'Driver door',
  },
  passengerDoor: {
    node: 'hinge_doorFrontRight',
    axis: 'y',
    openDegrees: -64,
    pivot: [0.905, 0.76, 0.955],
    label: 'Passenger door',
  },
  rearLeftDoor: {
    node: 'hinge_doorRearLeft',
    axis: 'y',
    openDegrees: 72,
    pivot: [-0.9, 0.76, -0.1],
    label: 'Rear left door',
  },
  rearRightDoor: {
    node: 'hinge_doorRearRight',
    axis: 'y',
    openDegrees: -72,
    pivot: [0.9, 0.76, -0.1],
    label: 'Rear right door',
  },
  rearTrunk: {
    node: 'hinge_liftgate',
    axis: 'x',
    openDegrees: 44,
    pivot: [0, 1.512, -1.52],
    label: 'Rear trunk',
  },
  frontTrunk: {
    node: 'hinge_frunkLid',
    axis: 'x',
    openDegrees: -52,
    pivot: [0, 1.062, 1.15],
    label: 'Front trunk',
  },
  chargePort: {
    node: 'hinge_chargePortFlap',
    axis: 'y',
    openDegrees: -105,
    pivot: [-0.905, 0.905, -1.7],
    label: 'Charge port',
  },
};

export const VEHICLE_PARTS = Object.keys(HINGES) as VehiclePart[];

/** Which door each semantic door part reports against. */
export const PART_DOOR: Partial<Record<VehiclePart, DoorId>> = {
  driverDoor: 'frontLeft',
  passengerDoor: 'frontRight',
  rearLeftDoor: 'rearLeft',
  rearRightDoor: 'rearRight',
};

/** Light-emitting node names, grouped by what switches them on. */
export const LIGHT_GROUPS = {
  headlights: ['headlightLeft', 'headlightRight'],
  daytimeRunning: ['daytimeRunningBar'],
  taillights: ['taillightLeft', 'taillightRight', 'taillightBar'],
  indicators: [
    'indicatorFrontLeft',
    'indicatorFrontRight',
    'indicatorRearLeft',
    'indicatorRearRight',
  ],
} as const;

export type LightGroup = keyof typeof LIGHT_GROUPS;

/** Emissive colour per group, so a flash lights the right surfaces. */
export const LIGHT_COLOUR: Record<LightGroup, number> = {
  headlights: 0xdfe9ff,
  daytimeRunning: 0xcfe0ff,
  taillights: 0xff2d24,
  indicators: 0xff9a1f,
};

/**
 * Target pose: where each part should be, expressed as 0 (closed) to 1 (open).
 *
 * This is derived ONLY from vehicle-reported state. It is deliberately a pure
 * function so the renderer can never invent a position — if the vehicle has not
 * reported a door as open, the door is drawn closed.
 */
export type VehiclePose = Record<VehiclePart, number>;

export const CLOSED_POSE: VehiclePose = {
  driverDoor: 0,
  passengerDoor: 0,
  rearLeftDoor: 0,
  rearRightDoor: 0,
  rearTrunk: 0,
  frontTrunk: 0,
  chargePort: 0,
};

export const poseFromState = (state: VehicleState | null): VehiclePose => {
  if (!state) return CLOSED_POSE;
  return {
    driverDoor: state.doors.frontLeft === 'open' ? 1 : 0,
    passengerDoor: state.doors.frontRight === 'open' ? 1 : 0,
    rearLeftDoor: state.doors.rearLeft === 'open' ? 1 : 0,
    rearRightDoor: state.doors.rearRight === 'open' ? 1 : 0,
    rearTrunk: state.trunk === 'open' ? 1 : 0,
    frontTrunk: state.frunk === 'open' ? 1 : 0,
    chargePort: state.charge.portOpen ? 1 : 0,
  };
};

/** True when any panel is reported away from its closed position. */
export const anyPartOpen = (pose: VehiclePose): boolean =>
  VEHICLE_PARTS.some((part) => pose[part] > 0.001);

/**
 * Reported lighting, as booleans per group.
 *
 * A flash is NOT included here — it is a transient event handled separately, so
 * that a flash can never leave a light stuck on.
 */
export const lightsFromState = (state: VehicleState | null): Record<LightGroup, boolean> => ({
  headlights: state?.lights.headlights ?? false,
  daytimeRunning: state?.lights.daytimeRunning ?? false,
  taillights: state?.lights.taillights ?? false,
  indicators: state?.lights.indicators ?? false,
});

/** Camera presets. Framing is chosen, never a free-running orbit. */
export type CameraPreset = 'hero' | 'exterior' | 'topDown' | 'cabin' | 'rear';

export type CameraSpec = {
  position: readonly [number, number, number];
  target: readonly [number, number, number];
  fov: number;
  label: string;
  /**
   * How much of the scene, in metres across, this preset must keep in frame.
   *
   * `fov` is vertical, so on a tall surface the horizontal view narrows and the
   * vehicle would overflow. The scene pushes the camera back until this width
   * fits. Omit it for an interior view, where filling the frame is the point.
   */
  framedWidth?: number;
};

// The vehicle is 4.751 m long, so a framed width of ~6 m leaves a comfortable
// margin at both bumpers; the top-down view needs more because it sees length
// across the frame's short axis on a portrait surface.
export const CAMERA_PRESETS: Record<CameraPreset, CameraSpec> = {
  hero: {
    position: [5.0, 2.05, 4.6],
    target: [0, 0.78, 0.05],
    fov: 28,
    label: 'Hero',
    framedWidth: 6.1,
  },
  exterior: {
    position: [6.1, 2.35, 5.4],
    target: [0, 0.8, 0],
    fov: 27,
    label: 'Exterior',
    framedWidth: 6.4,
  },
  topDown: {
    position: [0.02, 8.4, 0.9],
    target: [0, 0.4, 0],
    fov: 30,
    label: 'Top-down',
    framedWidth: 5.6,
  },
  cabin: { position: [-0.34, 1.3, -0.55], target: [-0.05, 1.0, 1.4], fov: 62, label: 'Cabin' },
  rear: {
    position: [-4.6, 2.1, -4.6],
    target: [0, 0.85, -0.4],
    fov: 29,
    label: 'Rear',
    framedWidth: 6.2,
  },
};

/**
 * Screen-space anchor for a part's hotspot, in model space.
 *
 * Projected through the live camera at render time rather than hard-coded to
 * image fractions, so a hotspot tracks its panel at every camera preset.
 */
export const HOTSPOT_ANCHOR: Record<VehiclePart, readonly [number, number, number]> = {
  driverDoor: [-0.96, 0.92, 0.42],
  passengerDoor: [0.96, 0.92, 0.42],
  rearLeftDoor: [-0.95, 0.92, -0.62],
  rearRightDoor: [0.95, 0.92, -0.62],
  rearTrunk: [0, 1.24, -2.16],
  frontTrunk: [0, 1.06, 1.64],
  chargePort: [-0.95, 0.9, -1.6],
};

/**
 * Projects a model-space anchor to a point inside a rendered box.
 *
 * Deliberately mirrors the camera spec used by the scene rather than reading
 * back from three.js: the presets are fixed, so the maths is deterministic and
 * a hotspot can be positioned without a frame callback pushing React state.
 *
 * Returns null when the anchor falls behind the camera or outside the frame.
 */
export type ProjectedPoint = { x: number; y: number; depth: number; facing: number };

export const projectAnchor = (
  anchor: readonly [number, number, number],
  preset: CameraPreset,
  width: number,
  height: number,
): ProjectedPoint | null => {
  if (width <= 0 || height <= 0) return null;
  const spec = CAMERA_PRESETS[preset];
  const eye = spec.position;
  const target = spec.target;

  const sub = (a: readonly number[], b: readonly number[]) =>
    [a[0]! - b[0]!, a[1]! - b[1]!, a[2]! - b[2]!] as [number, number, number];
  const norm = (v: [number, number, number]): [number, number, number] => {
    const m = Math.hypot(v[0], v[1], v[2]) || 1;
    return [v[0] / m, v[1] / m, v[2] / m];
  };
  const cross = (a: readonly number[], b: readonly number[]): [number, number, number] => [
    a[1]! * b[2]! - a[2]! * b[1]!,
    a[2]! * b[0]! - a[0]! * b[2]!,
    a[0]! * b[1]! - a[1]! * b[0]!,
  ];
  const dot = (a: readonly number[], b: readonly number[]) =>
    a[0]! * b[0]! + a[1]! * b[1]! + a[2]! * b[2]!;

  const forward = norm(sub(target, eye));
  const right = norm(cross(forward, [0, 1, 0]));
  const up = cross(right, forward);

  const d = sub(anchor, eye);
  const depth = dot(d, forward);
  if (depth <= 0.05) return null;

  const f = 1 / Math.tan((spec.fov * Math.PI) / 180 / 2);
  const aspect = width / height;
  const x = ((dot(d, right) * f) / aspect / depth) * 0.5 * width + width * 0.5;
  const y = height * 0.5 - ((dot(d, up) * f) / depth) * 0.5 * height;

  // `facing` is positive when the anchor's outward direction points toward the
  // camera. Used to hide hotspots on the far side of the body rather than
  // letting them float over bodywork they are not attached to.
  const outward = norm([anchor[0], 0, anchor[2] * 0.35]);
  const toCamera = norm(sub(eye, anchor));
  const facing = dot(outward, toCamera);

  return { x, y, depth, facing };
};

/**
 * Nudges overlapping hotspots apart vertically.
 *
 * Labels that collide are unreadable and, worse, ambiguous about which panel
 * they control — so a deterministic separation pass runs after projection.
 */
export const separateHotspots = <T extends { x: number; y: number }>(
  points: T[],
  minDistance = 46,
): T[] => {
  const sorted = [...points].sort((a, b) => a.y - b.y);
  for (let i = 1; i < sorted.length; i += 1) {
    const current = sorted[i]!;
    for (let j = 0; j < i; j += 1) {
      const other = sorted[j]!;
      const dx = Math.abs(current.x - other.x);
      const dy = Math.abs(current.y - other.y);
      if (dx < minDistance && dy < minDistance) {
        current.y = other.y + minDistance;
      }
    }
  }
  return sorted;
};
